### PR TITLE
[BUG][POLYFILL] Add better value modification handling in adapter + create class

### LINKED ISSUE #160: [BUG][POLYFILL] useLayout & useUser cause infinite rerender on MCP Apps host
- This is due to the `mcp-app-renderer.ts` that always create a new object when calling the getSnapshot method
- useSyncExternalStore compares object and decide to rerender if the object is different
- This is only on the userAgent & safeArea

### PR DESCRIPTION
**Pull request by qchuchu**
Fixes #160 + #152

<h3>Greptile Summary</h3>

Refactors bridge adapters from module exports to singleton classes, improving architecture and enabling better value management. The PR introduces a `BaseAdapter` class that both `AppsSdkAdapter` and `McpAppAdapter` extend, and adds deep equality checking with `dequal` to maintain referential stability for complex objects in the MCP adapter. This prevents unnecessary re-renders when object values haven't actually changed. The `requestDisplayMode` API is also simplified to accept the mode directly rather than wrapped in an object. Tests are expanded to cover both adapter types and verify the referential stability behavior.

<h3>Confidence Score: 4/5</h3>

- This PR is safe to merge with only minor optimization opportunities
- The refactoring is well-structured with proper singleton patterns, comprehensive tests covering both adapters, and the core functionality appears correct. The main issue is an inconsistency in how AppsSdkAdapter handles store caching compared to McpAppAdapter - it creates new objects on each call rather than caching them. While React's useSyncExternalStore should handle this gracefully, it's inefficient and inconsistent with the MCP adapter's approach. The deep equality checking with dequal is properly implemented for MCP, and all method signatures are correctly adapted.
- Pay attention to `packages/core/src/web/bridges/apps-sdk-adapter.ts` for the store caching optimization

### CODE REVIEW

File: packages/core/src/web/bridges/adaptors/apps-sdk-adaptor.ts [hunk 1]
```diff
@@ -1,19 +1,53 @@
...
+
+  public getExternalStore<K extends keyof BridgeInterface>(
+    key: K,
+  ): BridgeExternalStore<K> {
+    const bridge = AppsSdkBridge.getInstance();
+    return {
+      subscribe: bridge.subscribe(key),
+      getSnapshot: () => bridge.getSnapshot(key),
+    };
+  }
```
[the remark this answers is not in the document]
Comment (qchuchu) [reply packages/core/src/web/bridges/adaptors/apps-sdk-adaptor.ts:32]: Yes but it was already the case before no ? As we are destructuring after in the useSyncExternalStore we pass directly the methods. The only thing I see is that we always send a new getSnapshot method.

[the remark this answers is not in the document]
Comment (qchuchu) [reply packages/core/src/web/bridges/adaptors/apps-sdk-adaptor.ts:32]: It's too verbose and does not have any impact

File: packages/core/src/web/hooks/use-layout.test.ts [hunk 2]
```diff
@@ -1,61 +1,152 @@
...
+  describe("mcp-app host type", () => {
+    let mockPostMessage: ReturnType<typeof vi.fn>;
+
+    beforeEach(() => {
+      mockPostMessage = vi.fn();
+      Object.defineProperty(window, "parent", {
+        value: { postMessage: mockPostMessage },
+        writable: true,
+        configurable: true,
+      });
```
Comment (fredericbarthelet) [inline packages/core/src/web/hooks/use-layout.test.ts]: why not use your new host initializer mock here?

File: packages/core/src/web/hooks/use-layout.test.ts [hunk 3]
```diff
@@ -1,61 +1,152 @@
...
+      vi.stubGlobal("skybridge", { hostType: "mcp-app" });
+      McpAppBridge.resetInstance();
+      McpAppAdapter.resetInstance();
```
Comment (fredericbarthelet) [inline packages/core/src/web/hooks/use-layout.test.ts]: should be in after only

File: packages/core/src/web/hooks/use-layout.test.ts (hunk 2 above)
Comment (qchuchu) [reply packages/core/src/web/hooks/use-layout.test.ts]: My bad I didn't adapt the test

File: packages/core/src/web/hooks/use-layout.test.ts [hunk 4]
```diff
@@ -1,61 +1,152 @@
...
+        theme: "light",
+        viewport: { maxHeight: 500 },
+        safeAreaInsets: { top: 44, right: 0, bottom: 34, left: 0 },
+      });
+
+      await waitFor(() => {
+        expect(result.current.safeArea).toBeDefined();
+      });
+
+      const firstSafeAreaRef = result.current.safeArea;
```
Comment (fredericbarthelet) [inline packages/core/src/web/hooks/use-layout.test.ts]: I thought you were mentionning a React ref here. WDYT of `initialSafeArea` instead?

File: packages/core/src/web/hooks/use-user.test.ts [hunk 5]
```diff
@@ -1,56 +1,147 @@
...
+  describe("mcp-app host type", () => {
+    let mockPostMessage: ReturnType<typeof vi.fn>;
+
+    beforeEach(() => {
+      mockPostMessage = vi.fn();
+      Object.defineProperty(window, "parent", {
+        value: { postMessage: mockPostMessage },
+        writable: true,
+        configurable: true,
+      });
```
Comment (fredericbarthelet) [inline packages/core/src/web/hooks/use-user.test.ts]: same here

File: packages/core/src/web/hooks/use-user.test.ts [hunk 6]
```diff
@@ -1,56 +1,147 @@
...
+        locale: "en-US",
+        platform: "web",
+        deviceCapabilities: { hover: true, touch: false },
+      });
+
+      await waitFor(() => {
+        expect(result.current.userAgent).toBeDefined();
+      });
+
+      const firstUserAgentRef = result.current.userAgent;
```
Comment (fredericbarthelet) [inline packages/core/src/web/hooks/use-user.test.ts]: same here -> `initialUserAgent` ?

File: packages/core/src/web/bridges/apps-sdk-adapter.ts [hunk 7]
```diff
@@ -1,19 +1,58 @@
...
+    return window.openai.requestDisplayMode({ mode });
+  };
+
+  public sendFollowUpMessage = (prompt: string): Promise<void> => {
+    return window.openai.sendFollowUpMessage({ prompt });
+  };
+
+  public getMethod<K extends keyof Methods>(key: K) {
+    return this[key];
+  }
```
Comment (fredericbarthelet) [inline packages/core/src/web/bridges/apps-sdk-adapter.ts]: I don't understand the need for this method

File: packages/core/src/web/bridges/adaptors/mcp-app-adaptor.ts [hunk 8]
```diff
@@ -0,0 +1,197 @@
...
+        ) as PickContext<Keys>;
+        const newValue = computeSnapshot(context);
+
+        if (cachedValue !== undefined && dequal(cachedValue, newValue)) {
+          return cachedValue;
+        }
+
+        cachedValue = newValue;
+        return newValue;
+      },
```
Comment (fredericbarthelet) [inline packages/core/src/web/bridges/adaptors/mcp-app-adaptor.ts:194]: can't you just use `useCallback` from React on this monad in `getSnapshot` with a dependency to `context` to compute if a re-render is necessary?

File: packages/core/src/web/bridges/adaptors/mcp-app-adaptor.ts [hunk 9]
```diff
@@ -0,0 +1,197 @@
...
+          keys.map((k) => [k, bridge.getSnapshot(k)]),
+        ) as PickContext<Keys>;
+        const newValue = computeSnapshot(context);
+
+        if (cachedValue !== undefined && dequal(cachedValue, newValue)) {
+          return cachedValue;
+        }
+
+        cachedValue = newValue;
+        return newValue;
```
Comment (fredericbarthelet) [inline packages/core/src/web/bridges/adaptors/mcp-app-adaptor.ts:193]:
```suggestion
        return cachedValue;
```

Comment (fredericbarthelet) [reply packages/core/src/web/bridges/adaptors/mcp-app-adaptor.ts:193]: I don't understand where you set cachedValue in fact, and why it's a let

**Review by fredericbarthelet — APPROVED** [review]
